INSERT INTO permission (id, permission_name) VALUES
(1, 'CREATE_USER'),
(2, 'GET-USER-LIST'),
(3, 'CREATE_ROLE'),
(4, 'GET_ROLE_MANAGEMENT'),
(5, 'CREATE_API'),
(6, 'GET-API-LIST'),
(7, 'GET-PERMISSION-LIST'),
(8, 'GET_PROJECT_CONCEPTS'),
(9, 'CREATE_MENUS/ACTIONS')
ON CONFLICT
DO NOTHING;