export class ApplicationSubmission{
    data:string;
    application_subject:string;
    projectConceptUuid:string;
    feasibilityUuid:string;
    dppTappUuid:string;
    tappUuid:string;
    rdppUuid:string;
    rtappUuid:string;
    sourceModule:string;
    reportType:string;
    name:string;
    url:string;
    srcUserGroup:string;
    doptorToken:string;
    reportList:any[]=[];
    ppsUrl:string;
    workingPaperCreated:boolean;
}
