version: '3'
services:
  planning-idsdp-uaa:
    image: 'planning-idsdp-uaa'
    container_name: uaa
    environment:
    - TZ=Asia/Dhaka
    ports:
      - "8080:8080"
    #Volume mounted for database for the storage
    volumes:
      - planning-idsdp-uaa:/var/lib/docker/volumes/planning-idsdp-uaa/_data
    build:
      context: "./"
      dockerfile: "Dockerfile"
    restart: always

#Volumes for DB data
volumes:
  planning-idsdp-uaa:
