#Test
spring:
  profiles: testdev
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://202.161.191.133:4352/db_uaa_test
    username: dev
    password: Po$tGr3@321$%
    hikari:
      connectionTimeout: 30000
      minimumIdle: 5
      maximumPoolSize: 20
      poolName: SpringBootJPAHikariCP
      idleTimeout: 30000
      maxLifetime: 1800000
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

eureka:
  instance:
    preferIpAddress: true
    ip-address: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
