package com.ibcs.idsdp.dpptapp.approval_process_flow.model.domain;

public enum MovementStageEnum {
    AGENCY_DESK, //0
    AGENCY_HEAD, //1
    MINISTRY_HEAD, //2
    MINISTRY_DESK, //3
    PLANNING_COMMISSION_HEAD, //4
    PLANNING_COMMISSION_DESK, //5
    PLANNING_MINISTER, //6
    APPROVED_BY_PLANNING_MINISTER, //7
    ECNEC, //8
    APPROVED_BY_ECNEC, //9
    APPROVED_BY_MINISTRY, //10
    MINISTERIAL_MEETING_NOTICE, //11
    MINISTERIAL_MEETING_HELD, //12
    PROJECT_SCRUTINY_COMMITTEE_MEETING_NOTICE, //13
    PROJECT_SCRUTINY_COMMITTEE_MEETING_HELD, //14
    DPEC_MEETING_NOTICE, //15
    DPEC_MEETING_HELD, //16
    DSPEC_MEETING_NOTICE, //17
    DSPEC_MEETING_HELD, //18
    REJECTED_BY_MINISTRY_DIVISION, //19
    UNDER_EXAMINE, //20
    PEC_MEETING_NOTICE, //21
    PEC_MEETING_HELD, //22
    POTRO_JARI_ATTACHED, //23
    ECNEC_OFFICERS, //24
    ECNEC_DESK, //25
    ECNEC_CONDITIONAL_APPROVE, //26
    UNAPPROVED_BY_ECNEC, //27
    POTRO_JARI_ATTACHED_IN_MINISTRY, //28
    POTRO_JARI_ATTACHED_IN_PLANCOMM, //29
    SPEC_MEETING_NOTICE, //30
    SPEC_MEETING_HELD //31

}
