version: '3.7'
services:
    planning-idsdp-rms-frontend:
        image: 'idsdp-rms-frontend'
        container_name: rms-frontend
        environment:
            - TZ=Asia/Dhaka
        networks:
         - sdpp01_fr_net
        ports:
            - "2100:3000"
        restart: always
        build:
            context: "./"
            dockerfile: "Dockerfile"
networks:
   sdpp01_fr_net:
     name: sdpp01_fr_net
