spring:
  application:
    name: planning-idsdp-rms-rpm-backend
  profiles:
    active: ${spring.cloud.config.profile}
  mvc:
    servlet:
      path: /rms-rpm/
  # cache properties
  jpa:
    properties:
      javax:
        persistence:
          sharedCache:
            #required - enable selective caching mode - only entities with @Cacheable annotation will use L2 cache.
            mode: ENABLE_SELECTIVE
      hibernate:
        format_sql: true
        generate_statistics: false
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          auth: true
    host: smtp.gmail.com
    username: ssrc.gov.bd@gmail.com
    protocol: smtp
    password: njkgrnguqjckktiy
    test-connection: false
    port: 587
    default-encoding: UTF-8

server:
  port: 7002

#logging:
#  file:
#      name: D:/sample.log

minio:
  host: http://202.161.191.131:9403


