version: '3'
services:
  planning-idsdp-pps-backend:
    image: 'planning-idsdp-pps-dpp-backend'
    container_name: pps-dpp-backend
    environment:
      - TZ=Asia/Dhaka
    ports:
      - "8087:8087"
    #Volume mounted for database for the storage
    volumes:
      - planning-idsdp-pps-dpp-backend:/var/lib/docker/volumes/planning-idsdp-pps-dpp-backend/_data
    build:
      context: "./"
      dockerfile: "Dockerfile"
    restart: always
#Volumes for DB data
volumes:
  planning-idsdp-pps-dpp-backend:
